In [24]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder, MinMaxScaler, StandardScaler
import numpy as np

# 데이터셋 로드
df = pd.read_csv('diamonds.csv')

# 범주형 변수 확인
categorical_columns = df.select_dtypes(include=['object']).columns

In [25]:
# 3.1.1 Ordinal Encoding
ordinal_encoder = OrdinalEncoder()
df[categorical_columns] = ordinal_encoder.fit_transform(df[categorical_columns])

In [26]:
# 3.1.2 One-Hot Encoding
one_hot_encoder = OneHotEncoder(sparse=False)
cut_encoded = one_hot_encoder.fit_transform(df[['cut']])
print("One-Hot Encoded 'cut' variable's first 5 samples:\n", cut_encoded[:5])

One-Hot Encoded 'cut' variable's first 5 samples:
 [[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]]


C:\Users\heal\AppData\Roaming\Python\Python38\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [27]:
# 연속형 변수 확인
continuous_columns = df.select_dtypes(include=[np.number]).columns
# 3.2.1 MinMaxScaling
min_max_scaler = MinMaxScaler()
df[continuous_columns] = min_max_scaler.fit_transform(df[continuous_columns])
print("\nFirst five rows after MinMaxScaling:\n", df.head())


First five rows after MinMaxScaling:
       carat   cut     color   clarity     depth     table     price       'x'  \
0  0.006237  0.50  0.166667  0.428571  0.513889  0.230769  0.000000  0.367784   
1  0.002079  0.75  0.166667  0.285714  0.466667  0.346154  0.000000  0.362197   
2  0.006237  0.25  0.166667  0.571429  0.386111  0.423077  0.000054  0.377095   
3  0.018711  0.75  0.833333  0.714286  0.538889  0.288462  0.000433  0.391061   
4  0.022869  0.25  1.000000  0.428571  0.563889  0.288462  0.000487  0.404097   

        'y'       'z'  
0  0.067572  0.076415  
1  0.065195  0.072642  
2  0.069100  0.072642  
3  0.071817  0.082704  
4  0.073854  0.086478  


In [28]:
# 데이터셋 다시 로드하여 StandardScaling 수행
df = pd.read_csv('diamonds.csv')
# 3.1.1 Ordinal Encoding 다시 수행 (StandardScaling에 앞서 필요)
df[categorical_columns] = ordinal_encoder.fit_transform(df[categorical_columns])

In [29]:
# 3.2.2 StandardScaling
standard_scaler = StandardScaler()
df[continuous_columns] = standard_scaler.fit_transform(df[continuous_columns])
print("\nFirst five rows after StandardScaling:\n", df.head())


First five rows after StandardScaling:
       carat       cut     color   clarity     depth     table     price  \
0 -1.198168 -0.538099 -0.937163 -0.484264 -0.174092 -1.099672 -0.904095   
1 -1.240361  0.434949 -0.937163 -1.064117 -1.360738  1.585529 -0.904095   
2 -1.198168 -1.511147 -0.937163  0.095589 -3.385019  3.375663 -0.903844   
3 -1.071587  0.434949  1.414272  0.675442  0.454133  0.242928 -0.902090   
4 -1.029394 -1.511147  2.002131 -0.484264  1.082358  0.242928 -0.901839   

        'x'       'y'       'z'  
0 -1.587837 -1.536196 -1.571129  
1 -1.641325 -1.658774 -1.741175  
2 -1.498691 -1.457395 -1.741175  
3 -1.364971 -1.317305 -1.287720  
4 -1.240167 -1.212238 -1.117674  
